name: 🚀 Deploy to AWS S3 + CloudFront

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '18'

jobs:
  deploy:
    name: 🌐 Deploy to AWS
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout код
      uses: actions/checkout@v4

    - name: 🟢 Настройка Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: 📦 Установка зависимостей
      run: |
        npm ci
        echo "✅ Зависимости установлены"

    - name: 🔍 Проверка качества кода
      run: |
        echo "🔍 Проверяем TypeScript..."
        npx tsc --noEmit || echo "⚠️ TypeScript warnings found, continuing..."
        echo "✅ Проверки завершены"

    - name: 🏗️ Сборка проекта
      run: |
        echo "🏗️ Начинаем сборку React приложения..."
        npm run build
        echo "✅ Сборка завершена успешно!"
        ls -la build/
      env:
        CI: false
        GENERATE_SOURCEMAP: false

    - name: 🔧 Настройка AWS CLI
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: 📤 Синхронизация с S3
      run: |
        echo "📤 Загружаем файлы в S3 bucket: ${{ secrets.S3_BUCKET_NAME }}"
        
        # Загружаем все файлы кроме HTML с длительным кэшированием
        aws s3 sync build/ s3://${{ secrets.S3_BUCKET_NAME }} \
          --delete \
          --cache-control "max-age=31536000,public" \
          --exclude "*.html" \
          --exclude "*.json"
        
        # Загружаем HTML файлы без кэширования
        aws s3 sync build/ s3://${{ secrets.S3_BUCKET_NAME }} \
          --cache-control "max-age=0,no-cache,no-store,must-revalidate" \
          --include "*.html" \
          --include "*.json"
        
        echo "✅ Файлы успешно загружены в S3"

    - name: 🔄 Инвалидация CloudFront кэша
      run: |
        echo "🔄 Очищаем CloudFront кэш..."
        INVALIDATION_ID=$(aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
          --paths "/*" \
          --query 'Invalidation.Id' \
          --output text)
        
        echo "🔄 Инвалидация запущена с ID: $INVALIDATION_ID"
        echo "⏳ Ожидаем завершения инвалидации..."
        
        aws cloudfront wait invalidation-completed \
          --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
          --id $INVALIDATION_ID
        
        echo "✅ Инвалидация CloudFront завершена!"

    - name: 🎉 Деплой завершен
      run: |
        echo "🎉 Деплой успешно завершен!"
        echo "🌐 Ваш сайт доступен по адресу:"
        echo "   https://${{ secrets.CLOUDFRONT_DOMAIN }}"
        echo ""
        echo "📊 Статистика деплоя:"
        echo "   📦 Собрано файлов: $(find build -type f | wc -l)"
        echo "   📤 Загружено в S3: ${{ secrets.S3_BUCKET_NAME }}"
        echo "   🔄 CloudFront обновлен: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}"

    - name: 💬 Комментарий в PR (если применимо)
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🚀 **Preview Deploy готов!**
            
            🌐 **URL:** https://${{ secrets.CLOUDFRONT_DOMAIN }}
            
            ✅ Изменения развернуты и готовы к тестированию.`
          })
